### ISSUE TITLE
url requested not found

### ISSUE THREAD

**Issue by flyingBurman** [plotly/dash-goldman-sachs-report-demo#2]
I try running this code and get "Not Found" error, as shown in below. Help ?

![image](https://user-images.githubusercontent.com/7884934/33039578-67d920a4-ce06-11e7-95fc-7a164f964ce2.png)

**Comment by chriddyp** [comment]
Try visiting http://127.0.0.1:5000/dash/gallery/goldman-sachs-report/ instead (they're prefixed under a separate URL for our proxy servers)

**Comment by chriddyp** [comment]
Or just remove the url base pathname on this line: https://github.com/plotly/dash-goldman-sachs-report-demo/blob/master/app.py#L61
